### ISSUE TITLE
Console Always Print Error Info

### ISSUE THREAD

**Issue by asfork** [swdotcom/swdc-sublime#17] opened 2020-08-09 12:32 UTC
**Describe the bug**
Console always print error info.

```paste below
plugins loaded
Error reading package info: [Errno 20] Not a directory: '/Users/***/Library/Application Support/Sublime Text 3/Installed Packages/CodeTime.sublime-package/lib/../package.json'
Error reading package info: [Errno 20] Not a directory: '/Users/***/Library/Application Support/Sublime Text 3/Installed Packages/CodeTime.sublime-package/lib/../package.json'
Code Time: Loaded v2.2.1 of package name: CodeTime
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Open Sublime Text
2. Show Console
3. See error info

**Desktop (please complete the following information):**
 - OS: macOS
 - Plugin version: Code Time v2.2.1

**Comment by bjacobson26** [comment] 2020-08-31 22:16
Hi @asfork - thank you for reporting this issue. It should be resolved in the latest release v2.3.2. I'm going to close this issue for now since we're unable to reproduce this error. If the error persists for you, please feel free to re-open the issue and let us know! thank you.

**Closed by bjacobson26** 2020-08-31 22:16 UTC
Labels: bug
